"""Dagster orchestration for EU Grid Pulse.

Turns the whole pipeline into one asset graph:

    ingest_raw ──► (dbt: stg_* ─► dim_*/fact_*)  ──► dashboard
                                                  └─► powerbi_export

- `ingest_raw` lands raw ENTSO-E (or synthetic) data into DuckDB.
- `dbt_models` is generated by dagster-dbt from the dbt project — one asset per
  model, and the 31 dbt tests surface as Dagster *asset checks*.
- `dashboard` / `powerbi_export` are the serving layer.

Run the UI with:  dagster dev -m src.dagster_defs   (then open http://localhost:3000)
A daily schedule (06:00) re-materialises everything incrementally.
"""
import os
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
# Make this venv's console scripts (dbt, etc.) resolvable even in Dagster's
# gRPC code-server subprocess, which doesn't inherit the shell PATH.
_SCRIPTS = str(_ROOT / ".venv" / ("Scripts" if os.name == "nt" else "bin"))
os.environ["PATH"] = _SCRIPTS + os.pathsep + os.environ.get("PATH", "")
_DBT_EXE = str(Path(_SCRIPTS) / ("dbt.exe" if os.name == "nt" else "dbt"))
# dbt (via dagster) needs to find the DuckDB warehouse and the profiles.yml.
os.environ.setdefault("DUCKDB_PATH", str(_ROOT / "data" / "eu_grid_pulse.duckdb"))
os.environ.setdefault("DBT_PROFILES_DIR", str(_ROOT / "dbt"))

from dagster import (
    AssetExecutionContext,
    AssetKey,
    AssetSpec,
    Definitions,
    MaterializeResult,
    MetadataValue,
    ScheduleDefinition,
    asset,
    define_asset_job,
    multi_asset,
)
from dagster_dbt import DagsterDbtTranslator, DbtCliResource, DbtProject, dbt_assets

from .dashboard import build as build_dashboard
from .export_powerbi import export as export_powerbi
from .ingest import extract_entsoe as extract
from .run_pipeline import ingest as run_ingest

# --- dbt project (prepares the manifest automatically in `dagster dev`) --------
dbt_project = DbtProject(project_dir=_ROOT / "dbt")
dbt_project.prepare_if_dev()


class _Translator(DagsterDbtTranslator):
    """Map each dbt source to a Dagster asset key matching its table name
    (raw_load / raw_generation), so the dbt graph connects to the ingestion
    multi-asset below."""

    def get_asset_key(self, dbt_resource_props: dict) -> AssetKey:
        if dbt_resource_props["resource_type"] == "source":
            return AssetKey(dbt_resource_props["name"])
        return super().get_asset_key(dbt_resource_props)


# --- Assets -------------------------------------------------------------------
@multi_asset(
    specs=[
        AssetSpec("raw_load", group_name="ingestion"),
        AssetSpec("raw_generation", group_name="ingestion"),
    ],
    compute_kind="python",
)
def raw_tables(context: AssetExecutionContext):
    """Pull load + generation for every country into the DuckDB raw tables.
    One ingestion pass writes both raw tables (incremental + idempotent)."""
    mode = "synthetic" if extract.use_synthetic() else "real (ENTSO-E)"
    rows = run_ingest()
    meta = {"mode": MetadataValue.text(mode), "raw_rows_written": MetadataValue.int(rows)}
    yield MaterializeResult(asset_key="raw_load", metadata=meta)
    yield MaterializeResult(asset_key="raw_generation", metadata=meta)


@dbt_assets(manifest=dbt_project.manifest_path, dagster_dbt_translator=_Translator())
def dbt_models(context: AssetExecutionContext, dbt: DbtCliResource):
    """staging + marts models, with dbt tests surfaced as asset checks."""
    yield from dbt.cli(["build"], context=context).stream()


_MARTS = [AssetKey(m) for m in ("fact_load", "fact_generation", "dim_country", "dim_fuel", "dim_date")]


@asset(deps=_MARTS, compute_kind="python", group_name="serving")
def dashboard(context: AssetExecutionContext) -> MaterializeResult:
    """Build the HTML dashboard from the marts."""
    out = build_dashboard()
    return MaterializeResult(metadata={"path": MetadataValue.path(str(out))})


@asset(deps=_MARTS, compute_kind="python", group_name="serving")
def powerbi_export(context: AssetExecutionContext) -> MaterializeResult:
    """Export the marts to Parquet + CSV for Power BI."""
    files = export_powerbi()
    return MaterializeResult(metadata={"files_written": MetadataValue.int(len(files))})


# --- Job + daily schedule -----------------------------------------------------
refresh_job = define_asset_job("daily_refresh", selection="*")
daily_schedule = ScheduleDefinition(job=refresh_job, cron_schedule="0 6 * * *")

defs = Definitions(
    assets=[raw_tables, dbt_models, dashboard, powerbi_export],
    jobs=[refresh_job],
    schedules=[daily_schedule],
    resources={"dbt": DbtCliResource(project_dir=dbt_project, dbt_executable=_DBT_EXE)},
)
